### ISSUE TITLE
스냅샷 기능

### ISSUE THREAD

**Issue by JunHyeong-99** [Familing/familing-backend#17]
## description
스냅샷 설정, 조회, 등록 기능을 구현한다.

## Todo

- [x] ~스냅샷 시간 설정~ 

- [x] 가족 스냅샷 목록 조회
    - [x] 특정 날짜기준으로 스냅샷기록 페이지네이션 제공
    - [x] 오늘 날짜 스냅샷 조회

- [x] 스냅샷 등록
