### ISSUE TITLE
상태보기 기능 enum으로 수정

### ISSUE THREAD

**Issue by JunHyeong-99** [Familing/familing-backend#45]
## description
상태 보기 기능에서 유저의 상태를 entitiy에서 enum타입으로 수정한다.

## Todo

- [ ] enum 타입 생성
- [ ] postman에 테스트하고 예시 남기기
- [ ] 테스트 코드 작성하기

**Comment by JunHyeong-99** [comment]
나중에 사용자의 커스텀한 상태기능을 구현하기 위해선 enum보단 entity로 관리하는게 좋아보입니다.
